- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart Copyparty
  ansible.builtin.systemd_service:
    name: copyparty
    state: restarted
  become: true
