- name: Write message of the day
  ansible.builtin.template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: "0644"
  become: true

- name: Write ssh hardening config
  ansible.builtin.template:
    src: templates/99_ssh_hardening.conf
    dest: /etc/ssh/sshd_config.d
    validate: /usr/sbin/sshd -t -f %s
    mode: "0644"
  notify: Restart sshd
  become: true

- name: Write tmux config file
  ansible.builtin.template:
    src: templates/.tmux.conf
    dest: /home/simsine
    mode: "0644"
  become: false

- name: Install common packages
  ansible.builtin.apt:
    pkg:
      - htop
      - ncdu
      - nmap
      - tmux
      - fastfetch
