- name: Write HAProxy config
  ansible.builtin.template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy
    mode: "0644"
    validate: /usr/sbin/haproxy -c -f %s
  become: true
  # notify: Restart HAProxy

- name: Enable HAProxy service
  ansible.builtin.systemd_service:
    name: haproxy
    enabled: false
    state: stopped
  become: true
