AllowUsers {{ default_username }}
AcceptEnv LANG LC_*
AuthenticationMethods publickey
PermitRootLogin no

PubkeyAuthentication yes
ChallengeResponseAuthentication no
PasswordAuthentication no
RSAAuthentication no
GSSAPIAuthentication no
HostbasedAuthentication no

AllowAgentForwarding no
X11Forwarding no
GatewayPorts no

Compression yes
UsePAM yes
PrintMotd no
