---
- name: Common configs
  hosts: all
  roles:
    - common
    - role: community.beszel.agent
      vars:
        agent_public_key: "{{ beszel_agent_public_key }}"
        agent_token: "{{ beszel_agent_token }}"
        agent_hub_url: "{{ beszel_agent_hub_url }}"
  become: true

- name: Glados config
  become: true
  hosts:
    - glados
  roles:
    - headscale
    - nginx
    - yatzy
    - copyparty
    - kuma
    - role: community.beszel.hub

- name: Adventure config
  become: true
  hosts:
    - adventure
  roles:
    - common

- name: Wheatley config
  become: true
  hosts:
    - wheatley
  roles:
    - common
