- name: Write yatzy service
  ansible.builtin.template:
    src: templates/yatzy.service
    dest: /etc/systemd/system
    mode: "0644"
  become: true

- name: Write yatzy socket
  ansible.builtin.template:
    src: templates/yatzy.socket
    dest: /etc/systemd/system
    mode: "0644"
  become: true

- name: Enable yatzy service
  ansible.builtin.systemd_service:
    name: yatzy
    enabled: true
  become: true

- name: Enable yatzy socket
  ansible.builtin.systemd_service:
    name: yatzy.socket
    enabled: false
  become: true
