# ! Notice: Comments following text must have two spaces of separation
[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # and enable multimedia indexing
  ansi   # and colors in log messages

  # uncomment the line starting with q, lo: to log to a file instead of stdout/journalctl;
  # $LOGS_DIRECTORY is usually /var/log/copyparty (comes from systemd)
  # and copyparty replaces %Y-%m%d with Year-MonthDay, so the
  # full path will be something like /var/log/copyparty/2023-1130.txt
  # (note: enable compression by adding .xz at the end)
  # q, lo: $LOGS_DIRECTORY/%Y-%m%d.log

  # p: 80,443,3923   # listen on 80/443 as well (requires CAP_NET_BIND_SERVICE)
  # i: 127.0.0.1     # only allow connections from localhost (reverse-proxies)
  i: unix:770:/dev/shm/copyparty.sock  # Publish unix port
  # ftp: 3921        # enable ftp server on port 3921
  # p: 3939          # listen on another port
  df: 16           # stop accepting uploads if less than 16 GB free disk space
  ver              # show copyparty version in the controlpanel
  # grid             # show thumbnails/grid-view by default
  theme: 2         # monokai
  name: simsine files  # change the server-name that's displayed in the browser
  # stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
  no-robots, force-js  # make it harder for search engines to read your server
  
  rproxy: -1  ### Client ips proxied
  xff-src: lan  ### Trusted proxy ips
  xff-hdr: X-Real-IP

[accounts]
  {{ default_username }}: {{ copyparty_pass }}  # username: password

[/]
  /files/pub
  accs:
    r: *  # Everyone can read folder
    rwmda: {{ default_username }}  # Admin can use all features

[/share]
  /files/share
  accs:
    g: *  # Everyone can get containing files
    rwmda: {{ default_username }}  # Admin can use all features
  flags:
    fk: 8  # filekey support for secret access

[/priv]
  /files/priv
  accs:
    rwmda: {{ default_username }}  # Admin can use all features
